# Generated by Django 5.0.6 on 2024-05-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='PracticeModel',
        ),
    ]
